CREATE TABLE board_spaces (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  board_id INTEGER NOT NULL,
  type VARCHAR(255) NOT NULL,
  sort INTEGER NOT NULL,
  action VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE
);
